version: "3"

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle:cached
